// dati i nomi di tre fratelli e dei loro genitori scrivere una frase completa di punteggiatura che informi l' utente sul rapporto di parentela tra i tre

// definisco tre variabili
let fratelli = " Luigi , Paolo e Concetta"
let genitori = " Zoe e Mohamet"
let frase 

// definisco tre variabili con i nomi dei fratelli
let figlio1 = "Luigi"
let figlio2 = "Paolo"
let figlio3 = "Concetta"

// definisco due variabili con i nomi dei genitori
let Zoe
let Mohamet

// preparo una frase del tipo
// "Luigi , Paolo e Concetta sono figli di Zoe e Mohamet" .
frase = fratelli + " sono figli di" + genitori + ".";

console.log(frase)
